### ISSUE TITLE
Can't build with GHC 8.8.4

### ISSUE THREAD

**Issue by ysangkok** [cmk/profunctor-optics#31]
Which version was this tested with? I tried building version 0.0.1 on GHC 8.8.4 and I got this error:

```
[ 3 of 23] Compiling Data.Profunctor.Optic.Index ( src/Data/Profunctor/Optic/Index.hs, dist/build/Data/Profunctor/Optic/Index.o )

src/Data/Profunctor/Optic/Index.hs:151:10: error:
    • The type synonym ‘Cx'’ should have 3 arguments, but has been given 1
    • In the type signature: kunit :: Strong p => Cx' p :-> p
    |
151 | kunit :: Strong p => Cx' p :-> p
    |          ^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build profunctor-optics-0.0.1
```

Thanks for your patience, it looks like exactly what I was looking for!

**Comment by cmk** [comment]
Sorry for the late reply: 0.0.1 was written with GHC 8.6.3. 

Probably obvious, but this library is not exactly stable :). I wouldn't recommend depending on it for anything too serious.
